# Generated by Django 4.2.4 on 2023-08-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.CharField(max_length=10, verbose_name="Класс"),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(max_length=10, verbose_name="Предмет"),
        ),
        migrations.CreateModel(
            name="StudentTeachers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="school.student",
                        verbose_name="студент",
                    ),
                ),
                (
                    "teacher_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="school.teacher",
                        verbose_name="учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учитель студента",
                "verbose_name_plural": "Учителя студентов",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="mentors",
            field=models.ManyToManyField(
                through="school.StudentTeachers", to="school.teacher"
            ),
        ),
    ]
